stages:
  - deploy
deploy:
    stage: deploy
    environment:
        name: test
    script:
    - git pull https://github.com/PuppiesMeat/JetpackGo.git master --rebase 

    only:
      - master
    tags:
      - shell